# Generated by Django 4.2.19 on 2025-02-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0003_news_description_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineShopApp.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
