# Generated by Django 4.2.19 on 2025-02-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0010_remove_product_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
