# Generated by Django 4.2.19 on 2025-02-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
