# Generated by Django 4.2.19 on 2025-02-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0012_phoneverificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['created_at']},
        ),
    ]
