# Generated by Django 4.2.19 on 2025-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0013_alter_basketitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
