# Generated by Django 4.2.19 on 2025-03-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0014_customuser_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Bekor qilindi', 'Bekor qilindi'), ('Jarayonda', 'Jarayonda'), ('Yetkazib berildi', 'Yetkazib berildi')], default='Jarayonda', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='OnlineShopApp.order'),
        ),
    ]
