# Generated by Django 4.2.19 on 2025-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0015_alter_order_options_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/mobile/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/mobile/'),
        ),
    ]
