# Generated by Django 4.2.19 on 2025-04-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0017_news_new_type_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_image1',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_image2',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_image3',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_image4',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_image5',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
