# Generated by Django 4.2.19 on 2025-05-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0020_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('mahsus_taklif', 'Mahsus taklif'), ('yangilik', 'Yangilik')], default='yangilik', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status_ru',
            field=models.CharField(blank=True, choices=[('special', 'Специальное'), ('new', 'Новое')], default='new', max_length=20, null=True),
        ),
    ]
